// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login dengan email dan password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Generate new access token using refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/cdn/mentor": {
            "get": {
                "description": "Get list mentor images from storage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CDN"
                ],
                "summary": "Get mentor images",
                "responses": {}
            }
        },
        "/cdn/modul": {
            "get": {
                "description": "Get list modul images from storage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CDN"
                ],
                "summary": "Get modul images",
                "responses": {}
            }
        },
        "/cdn/news": {
            "get": {
                "description": "Get list news images and links",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CDN"
                ],
                "summary": "Get news",
                "responses": {}
            }
        },
        "/materi/peserta/private": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list materi private berdasarkan modul",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Materi"
                ],
                "summary": "Get materi private peserta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter tipe materi (video | document)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/materi/peserta/{id_modul}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list materi berdasarkan modul",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Materi"
                ],
                "summary": "Get materi peserta",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Modul",
                        "name": "id_modul",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter tipe materi (video | document)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/modul/peserta": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of modules for the logged-in user based on their role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Module"
                ],
                "summary": "Get modules for a user",
                "responses": {}
            }
        },
        "/tryout/attempt/{attempt_token}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ambil semua soal untuk attempt",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get soal tryout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attempt Token",
                        "name": "attempt_token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/attempt/{attempt_token}/answers": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menyimpan jawaban peserta secara berkala",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Autosave jawaban tryout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attempt Token",
                        "name": "attempt_token",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Answers",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tryout.SaveAnswerRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/attempt/{attempt_token}/resume": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melanjutkan attempt yang sedang berjalan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Resume tryout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attempt Token",
                        "name": "attempt_token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/attempt/{attempt_token}/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submit hasil tryout peserta",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Submit tryout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attempt Token",
                        "name": "attempt_token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/peserta": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list tryout berdasarkan kelas peserta",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get tryout peserta",
                "responses": {}
            }
        },
        "/tryout/question/{id_soal}/choices": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get answer distribution for a question",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get question choice analysis",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id_soal",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Class ID (Optional for admin \u0026 mentor)",
                        "name": "class_id",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/report": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get laporan tryout",
                "responses": {}
            }
        },
        "/tryout/report/{attempt_token}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get pembahasan tryout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attempt Token",
                        "name": "attempt_token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/{id_tryout}/distribution": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Distribusi nilai tryout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get score distribution",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Tryout",
                        "name": "id_tryout",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Class ID",
                        "name": "class_id",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/{id_tryout}/leaderboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Leaderboard seluruh peserta berdasarkan tryout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get global leaderboard",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Tryout",
                        "name": "id_tryout",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/{id_tryout}/leaderboard/class": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Leaderboard berdasarkan kelas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get class leaderboard",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Tryout",
                        "name": "id_tryout",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Class ID (Admin \u0026 Mentor only)",
                        "name": "class_id",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/{id_tryout}/questions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get analysis for each question in a tryout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get question analysis",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tryout ID",
                        "name": "id_tryout",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Class ID (optional for admin \u0026 mentor)",
                        "name": "class_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort: default | hardest | easiest",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/{id_tryout}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Memulai tryout peserta",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Start tryout",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Tryout",
                        "name": "id_tryout",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/tryout/{id_tryout}/statistics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Statistik tryout (global / class)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tryout"
                ],
                "summary": "Get tryout statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Tryout",
                        "name": "id_tryout",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Class ID (Admin \u0026 Mentor only)",
                        "name": "class_id",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/user/change-password": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change user password (require old password)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Change password",
                "parameters": [
                    {
                        "description": "Change Password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/user/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get logged in user profile based on JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get current user",
                "responses": {}
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "auth.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "tryout.AnswerPayload": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "ragu": {
                    "type": "boolean"
                }
            }
        },
        "tryout.SaveAnswerRequest": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/tryout.AnswerPayload"
                    }
                }
            }
        },
        "user.ChangePasswordRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "UKAI Syndrome API V2",
	Description:      "API Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
