basePath: /api/v2
definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
      platform:
        type: string
    type: object
  auth.RefreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  tryout.AnswerPayload:
    properties:
      answer:
        type: string
      ragu:
        type: boolean
    type: object
  tryout.SaveAnswerRequest:
    properties:
      answers:
        additionalProperties:
          $ref: '#/definitions/tryout.AnswerPayload'
        type: object
    type: object
  user.ChangePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
info:
  contact: {}
  description: API Documentation
  title: UKAI Syndrome API V2
  version: "2.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login dengan email dan password
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses: {}
      summary: Login user
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Generate new access token using refresh token
      parameters:
      - description: Refresh Token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshRequest'
      produces:
      - application/json
      responses: {}
      summary: Refresh access token
      tags:
      - Auth
  /cdn/mentor:
    get:
      consumes:
      - application/json
      description: Get list mentor images from storage
      produces:
      - application/json
      responses: {}
      summary: Get mentor images
      tags:
      - CDN
  /materi/peserta/{id_modul}:
    get:
      consumes:
      - application/json
      description: Get list materi berdasarkan modul
      parameters:
      - description: ID Modul
        in: path
        name: id_modul
        required: true
        type: integer
      - description: Filter tipe materi (video | document)
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get materi peserta
      tags:
      - Materi
  /materi/peserta/private:
    get:
      consumes:
      - application/json
      description: Get list materi private berdasarkan modul
      parameters:
      - description: Filter tipe materi (video | document)
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get materi private peserta
      tags:
      - Materi
  /modul/peserta:
    get:
      consumes:
      - application/json
      description: Get a list of modules for the logged-in user based on their role
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get modules for a user
      tags:
      - Module
  /tryout/{id_tryout}/start:
    post:
      consumes:
      - application/json
      description: Memulai tryout peserta
      parameters:
      - description: ID Tryout
        in: path
        name: id_tryout
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Start tryout
      tags:
      - Tryout
  /tryout/attempt/{attempt_token}:
    get:
      consumes:
      - application/json
      description: Ambil semua soal untuk attempt
      parameters:
      - description: Attempt Token
        in: path
        name: attempt_token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get soal tryout
      tags:
      - Tryout
  /tryout/attempt/{attempt_token}/answers:
    put:
      consumes:
      - application/json
      description: Menyimpan jawaban peserta secara berkala
      parameters:
      - description: Attempt Token
        in: path
        name: attempt_token
        required: true
        type: string
      - description: Answers
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/tryout.SaveAnswerRequest'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Autosave jawaban tryout
      tags:
      - Tryout
  /tryout/attempt/{attempt_token}/resume:
    get:
      consumes:
      - application/json
      description: Melanjutkan attempt yang sedang berjalan
      parameters:
      - description: Attempt Token
        in: path
        name: attempt_token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Resume tryout
      tags:
      - Tryout
  /tryout/attempt/{attempt_token}/submit:
    post:
      consumes:
      - application/json
      description: Submit hasil tryout peserta
      parameters:
      - description: Attempt Token
        in: path
        name: attempt_token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Submit tryout
      tags:
      - Tryout
  /tryout/peserta:
    get:
      consumes:
      - application/json
      description: Get list tryout berdasarkan kelas peserta
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get tryout peserta
      tags:
      - Tryout
  /tryout/report:
    get:
      responses: {}
      security:
      - BearerAuth: []
      summary: Get laporan tryout
      tags:
      - Tryout
  /tryout/report/{attempt_token}:
    get:
      parameters:
      - description: Attempt Token
        in: path
        name: attempt_token
        required: true
        type: string
      responses: {}
      security:
      - BearerAuth: []
      summary: Get pembahasan tryout
      tags:
      - Tryout
  /user/change-password:
    put:
      consumes:
      - application/json
      description: Change user password (require old password)
      parameters:
      - description: Change Password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.ChangePasswordRequest'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Change password
      tags:
      - User
  /user/me:
    get:
      consumes:
      - application/json
      description: Get logged in user profile based on JWT
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
