basePath: /api/v2
definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
      platform:
        type: string
    type: object
  auth.RefreshRequest:
    properties:
      refresh_token:
        type: string
    type: object
  user.ChangePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
info:
  contact: {}
  description: API Documentation
  title: UKAI Syndrome API V2
  version: "2.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login dengan email dan password
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses: {}
      summary: Login user
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Generate new access token using refresh token
      parameters:
      - description: Refresh Token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshRequest'
      produces:
      - application/json
      responses: {}
      summary: Refresh access token
      tags:
      - Auth
  /materi/peserta/{id_modul}:
    get:
      consumes:
      - application/json
      description: Get list materi berdasarkan modul
      parameters:
      - description: ID Modul
        in: path
        name: id_modul
        required: true
        type: integer
      - description: Filter tipe materi (video | document)
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get materi peserta
      tags:
      - Materi
  /materi/peserta/private:
    get:
      consumes:
      - application/json
      description: Get list materi private berdasarkan modul
      parameters:
      - description: Filter tipe materi (video | document)
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get materi private peserta
      tags:
      - Materi
  /modul/peserta:
    get:
      consumes:
      - application/json
      description: Get a list of modules for the logged-in user based on their role
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get modules for a user
      tags:
      - Module
  /user/change-password:
    put:
      consumes:
      - application/json
      description: Change user password (require old password)
      parameters:
      - description: Change Password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.ChangePasswordRequest'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Change password
      tags:
      - User
  /user/me:
    get:
      consumes:
      - application/json
      description: Get logged in user profile based on JWT
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
